In [1]:
# !pip install gensim

In [1]:
import gensim

In [2]:
from gensim.models import Word2Vec,KeyedVectors

In [3]:
import gensim.downloader as api

In [4]:
wv=api.load('word2vec-google-news-300')

In [5]:
vec_king=wv['king']

In [6]:
vec_king.shape

(300,)

In [8]:
##wv.most_similar('cricket')

In [9]:
# wv.similarity('cricket','cricketer')

In [10]:
# vec=wv['king']-wv['man']+wv['queen']

In [11]:
# wv.most_similar([vec])

In [11]:
from nltk.stem import WordNetLemmatizer
lemetizer=WordNetLemmatizer()

In [12]:
import pandas as pd
import nltk
import re
messages=pd.read_csv('SMSSpamCollection',sep='\t',names=['label','message'])

In [13]:
corpus=[]
for i in range(0,len(messages)):
    #it says that apart of the alphabets liek a-z every thing replaced by blank
    review=re.sub('[^a-zA-Z]',' ',messages['message'][i])
    review=review.lower()
    review=review.split()
    review=[lemetizer.lemmatize(word) for word in review]
    review=' '.join(review)
    corpus.append(review)

In [14]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [15]:
from gensim.utils import simple_preprocess #it convets words into lower case
from nltk import sent_tokenize

In [16]:
words=[]
for sent in corpus:
    sent_token=sent_tokenize(sent)
    for s in sent_token:
        words.append(simple_preprocess(s))
        

In [17]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [18]:
#Lets train word2vec from scratch like google

In [19]:
# model.wv['go'].shape

In [20]:
model=gensim.models.Word2Vec(words,vector_size=100)

In [21]:
len(model.wv.index_to_key)

1721

In [22]:
model.corpus_count
##number of sentences

5569

In [23]:
model.epochs

5

In [24]:
model.wv.similar_by_word('good')

[('not', 0.9983912110328674),
 ('my', 0.998338520526886),
 ('wa', 0.9983128309249878),
 ('morning', 0.9983044862747192),
 ('night', 0.9982184171676636),
 ('and', 0.9981865286827087),
 ('about', 0.998068630695343),
 ('all', 0.9980500936508179),
 ('happy', 0.9980177879333496),
 ('well', 0.9979748129844666)]

In [25]:
model.wv['good']

array([-0.24994905,  0.25512758,  0.07940312,  0.0447983 ,  0.05470787,
       -0.6759172 ,  0.2333392 ,  0.72474056, -0.32630005, -0.22626828,
       -0.2271349 , -0.6332821 , -0.08413476,  0.00919687,  0.2614547 ,
       -0.2762843 ,  0.0711064 , -0.5129554 , -0.05173296, -0.7990212 ,
        0.34818676,  0.08755943,  0.20850246, -0.21783923, -0.02775721,
        0.10347969, -0.23724143, -0.36030078, -0.3714848 ,  0.03777079,
        0.43924704, -0.01589646,  0.21059366, -0.3121698 , -0.06384033,
        0.5145233 ,  0.01992707, -0.1661058 , -0.21266645, -0.67159426,
        0.12229075, -0.37542152, -0.32335716, -0.05909753,  0.24086475,
       -0.01823678, -0.24588269, -0.07304183,  0.22499628,  0.11919057,
        0.24956629, -0.33738637,  0.04942804,  0.08838059, -0.14314027,
        0.17047377,  0.20082413,  0.06725626, -0.61562514,  0.19884872,
        0.07350981,  0.1354511 , -0.11256209, -0.11434745, -0.41909593,
        0.344076  ,  0.10520054,  0.39067712, -0.40986565,  0.54

In [29]:
import numpy as np

In [28]:
words[0]

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [26]:
def avg_word2vec(doc):
    word_vectors = [model.wv[word] for word in doc if word in model.wv.index_to_key]
    if word_vectors:
        return np.mean(word_vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

In [27]:
!pip install tqdm

Defaulting to user installation because normal site-packages is not writeable


In [30]:
X=[]
from tqdm import tqdm
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))
    

100%|████████████████████████████████████████████████████████████████████████████| 5569/5569 [00:00<00:00, 6451.70it/s]


In [31]:
len(X)

5569

In [32]:
len(corpus)

5572

In [33]:
len(X)

5569

In [34]:
len(words)

5569

In [35]:
np.mean(model.wv['go'])

-0.0013368179

In [36]:
len(X)

5569

In [37]:
model.wv['go']

array([-0.29330254,  0.23784912,  0.10665124,  0.03100809,  0.10851206,
       -0.7899873 ,  0.23943183,  0.8106712 , -0.37070644, -0.26221266,
       -0.2956302 , -0.67651415, -0.15495314,  0.03226698,  0.28426123,
       -0.2841462 ,  0.0886322 , -0.58871865, -0.07848748, -0.8926397 ,
        0.293684  ,  0.08581472,  0.19975604, -0.24508744, -0.01434162,
        0.15232354, -0.31982207, -0.3942285 , -0.40129352,  0.06678092,
        0.4573575 ,  0.00267794,  0.17331237, -0.32632926, -0.0984502 ,
        0.54753375,  0.03666418, -0.18665558, -0.25736594, -0.7217187 ,
        0.1438272 , -0.4103534 , -0.3399585 , -0.01300554,  0.23864362,
       -0.05911775, -0.22747912, -0.07870219,  0.23825856,  0.1217307 ,
        0.22444256, -0.38063827,  0.11725999,  0.15883721, -0.25327235,
        0.19914228,  0.20039435,  0.05270267, -0.6480595 ,  0.24104741,
        0.14472091,  0.13904849, -0.09882943, -0.07586403, -0.45846665,
        0.38360095,  0.09046872,  0.39663416, -0.4542449 ,  0.57

In [43]:
import numpy as np
np.array(X)

array([[-0.17414293,  0.17591576,  0.06741228, ..., -0.2479829 ,
         0.17059855, -0.00899409],
       [-0.1620224 ,  0.1557356 ,  0.05780293, ..., -0.22732574,
         0.15488622, -0.0142811 ],
       [-0.18603541,  0.18378024,  0.08050013, ..., -0.27105892,
         0.1929398 ,  0.01441561],
       ...,
       [-0.23857485,  0.24042781,  0.08718245, ..., -0.32421473,
         0.22178163, -0.01649254],
       [-0.21141288,  0.21193135,  0.08009083, ..., -0.29696879,
         0.19904727, -0.01563873],
       [-0.23454829,  0.22788563,  0.08657702, ..., -0.32876739,
         0.21321185, -0.01127592]])

In [44]:
cor=[]
for i in X:
    cor.append(i)

In [45]:
np.array(X).shape

(5569, 100)

In [46]:
X[0]

array([-0.17414293,  0.17591576,  0.06741228,  0.02728414,  0.05249569,
       -0.502572  ,  0.16007261,  0.51064426, -0.22825779, -0.17929064,
       -0.1678126 , -0.44104767, -0.09731001,  0.01837211,  0.18489002,
       -0.18360455,  0.03559186, -0.37058565, -0.04157121, -0.55080473,
        0.20003976,  0.05346055,  0.12794358, -0.15964328, -0.01890213,
        0.07834045, -0.19216427, -0.23643318, -0.265109  ,  0.02754736,
        0.29181913, -0.00242885,  0.11990003, -0.22139023, -0.0556705 ,
        0.36394635,  0.04438445, -0.11877032, -0.18465728, -0.4691943 ,
        0.07737923, -0.25874394, -0.23212333, -0.03952851,  0.16289386,
       -0.03277888, -0.1561306 , -0.04063417,  0.17839643,  0.09034095,
        0.15578185, -0.24431065,  0.04161602,  0.08835426, -0.14869891,
        0.11457215,  0.13424046,  0.0317522 , -0.433409  ,  0.14148808,
        0.06913784,  0.09719361, -0.07244853, -0.07465947, -0.2980062 ,
        0.24600561,  0.05974507,  0.2572969 , -0.30588225,  0.36

In [47]:
X_New=np.array(X)

In [48]:
X_New.shape

(5569, 100)

In [49]:
y=messages['label']
y


0        ham
1        ham
2       spam
3        ham
4        ham
        ... 
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: label, Length: 5572, dtype: object

In [50]:
y=pd.get_dummies(messages['label'])
y

ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [51]:
y=y.iloc[:,0]

In [52]:
y

0        True
1        True
2       False
3        True
4        True
        ...  
5567    False
5568     True
5569     True
5570     True
5571     True
Name: ham, Length: 5572, dtype: bool

In [53]:
listr=["Hey baby","wanna dinner",'sexy baby']
list(map(len,listr))

[8, 12, 9]

In [54]:
list(map(len,corpus))

[102,
 23,
 126,
 43,
 57,
 135,
 74,
 147,
 126,
 135,
 106,
 99,
 128,
 191,
 33,
 142,
 22,
 74,
 54,
 121,
 40,
 44,
 44,
 83,
 55,
 137,
 29,
 125,
 72,
 59,
 128,
 175,
 28,
 83,
 154,
 111,
 46,
 28,
 21,
 150,
 78,
 121,
 137,
 18,
 59,
 27,
 44,
 29,
 66,
 142,
 56,
 110,
 79,
 278,
 112,
 70,
 121,
 32,
 22,
 38,
 102,
 44,
 24,
 53,
 108,
 130,
 114,
 124,
 73,
 33,
 37,
 28,
 44,
 39,
 17,
 41,
 71,
 46,
 35,
 72,
 21,
 29,
 32,
 36,
 13,
 50,
 115,
 139,
 42,
 37,
 55,
 187,
 136,
 106,
 100,
 129,
 31,
 48,
 168,
 31,
 55,
 75,
 73,
 147,
 176,
 44,
 91,
 42,
 82,
 107,
 28,
 39,
 30,
 88,
 124,
 131,
 138,
 116,
 67,
 82,
 100,
 121,
 50,
 125,
 47,
 33,
 18,
 237,
 21,
 103,
 24,
 8,
 37,
 24,
 110,
 141,
 37,
 33,
 42,
 143,
 71,
 32,
 25,
 141,
 40,
 25,
 46,
 140,
 83,
 31,
 27,
 43,
 53,
 19,
 147,
 363,
 27,
 24,
 149,
 109,
 115,
 115,
 59,
 82,
 128,
 148,
 48,
 127,
 72,
 63,
 55,
 48,
 78,
 31,
 95,
 56,
 65,
 25,
 129,
 65,
 122,
 151,
 21,
 63,
 21,
 26,
 139

In [55]:
for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']):
    if i<1:
        print(f"Short element found: Length={i}, Corpus='{j}', Message='{k}'")

Short element found: Length=0, Corpus='', Message='645'
Short element found: Length=0, Corpus='', Message=':) '
Short element found: Length=0, Corpus='', Message=':-) :-)'


In [56]:
len(y)

5572

In [57]:
#here my input data has 5569 value but y is 5572

In [59]:
# for i in list(map(len,corpus))

In [60]:
y=messages[list(map(lambda x : len(x)>0,corpus))]
y=pd.get_dummies(y['label'])
y=y.iloc[:,0]
y.shape

(5569,)

In [61]:
for i,j,k in zip(list(map(len,corpus)),corpus,messages['message']):
    if i<1:
        print(f"Short element found: Length={i}, Corpus='{j}', Message='{k}'")

Short element found: Length=0, Corpus='', Message='645'
Short element found: Length=0, Corpus='', Message=':) '
Short element found: Length=0, Corpus='', Message=':-) :-)'


In [62]:
X_New.shape,y.shape

((5569, 100), (5569,))

In [78]:
rows=[]
import pandas as pd
df=pd.DataFrame();
for i in range(len(X_New)):
    rows.append(X_New[i].reshape(1,-1)[0])

In [79]:
df=pd.DataFrame(rows)

In [80]:
df.head(1)

0         1         2         3         4         5         6   \
0 -0.174143  0.175916  0.067412  0.027284  0.052496 -0.502572  0.160073   

         7         8         9   ...        90        91        92        93  \
0  0.510644 -0.228258 -0.179291  ...  0.370665  0.116997  0.101708  0.049573   

         94        95       96        97        98        99  
0  0.479556  0.217372  0.15426 -0.247983  0.170599 -0.008994  

[1 rows x 100 columns]

In [81]:
df.shape

(5569, 100)

In [82]:
df.head()

0         1         2         3         4         5         6   \
0 -0.174143  0.175916  0.067412  0.027284  0.052496 -0.502572  0.160073   
1 -0.162022  0.155736  0.057803  0.025741  0.051802 -0.440523  0.128465   
2 -0.186035  0.183780  0.080500  0.041774  0.048102 -0.546281  0.166766   
3 -0.241109  0.237371  0.085433  0.042071  0.072115 -0.677683  0.207621   
4 -0.205710  0.194346  0.078621  0.031960  0.066545 -0.566104  0.176434   

         7         8         9   ...        90        91        92        93  \
0  0.510644 -0.228258 -0.179291  ...  0.370665  0.116997  0.101708  0.049573   
1  0.452668 -0.200198 -0.147856  ...  0.328945  0.094950  0.082847  0.035337   
2  0.505984 -0.243727 -0.207555  ...  0.369933  0.120951  0.092602  0.026484   
3  0.696718 -0.310400 -0.228294  ...  0.502454  0.151919  0.131225  0.070107   
4  0.588927 -0.262569 -0.199029  ...  0.425156  0.124911  0.117815  0.061233   

         94        95        96        97        98        99  
0  0.479556  0.217372  0.154260 -0.247983  0.170599 -0.008994  
1  0.410138  0.185470  0.135792 -0.227326  0.154886 -0.014281  
2  0.482740  0.201302  0.112477 -0.271059  0.192940  0.014416  
3  0.639014  0.298569  0.222938 -0.344516  0.231078 -0.019509  
4  0.536308  0.253888  0.182840 -0.295207  0.188991 -0.016305  

[5 rows x 100 columns]

In [84]:
df.shape,y.shape

((5569, 100), (5569,))

In [85]:
from sklearn.model_selection import train_test_split
X=df
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [86]:
y_train

3920     True
3988    False
2759     True
4798    False
4505     True
        ...  
3774     True
5194     True
5229     True
5393     True
860      True
Name: ham, Length: 4455, dtype: bool

In [87]:
from sklearn.ensemble import RandomForestClassifier
classifier=RandomForestClassifier()

In [89]:
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [90]:
y_pred=classifier.predict(X_test)

In [91]:
from sklearn.metrics import accuracy_score

In [92]:
print(accuracy_score(y_pred,y_test))

0.973967684021544


In [93]:
X_train.head()

0         1         2         3         4         5         6   \
3918 -0.184445  0.238848  0.076301  0.028138  0.037548 -0.592276  0.208415   
3986 -0.185622  0.189987  0.084143  0.032542  0.047091 -0.546003  0.166913   
2758 -0.222973  0.215729  0.086182  0.034532  0.070876 -0.626752  0.196155   
4796 -0.215674  0.229938  0.102448  0.044855  0.060716 -0.656448  0.203203   
4503 -0.217202  0.204147  0.079242  0.031819  0.067256 -0.599233  0.180651   

            7         8         9   ...        90        91        92  \
3918  0.624740 -0.267414 -0.223522  ...  0.440456  0.159356  0.161309   
3986  0.511829 -0.239866 -0.211944  ...  0.370616  0.122953  0.095299   
2758  0.631699 -0.281077 -0.227667  ...  0.459429  0.143101  0.118926   
4796  0.631921 -0.291703 -0.252012  ...  0.459583  0.144398  0.117110   
4503  0.611155 -0.274251 -0.213344  ...  0.444383  0.136618  0.119304   

            93        94        95        96        97        98        99  
3918  0.076846  0.593591  0.274100  0.212438 -0.260702  0.188206 -0.034929  
3986  0.031923  0.485238  0.206064  0.116912 -0.268933  0.189850  0.007856  
2758  0.067227  0.588718  0.273063  0.182156 -0.309313  0.212592 -0.006013  
4796  0.037784  0.598182  0.250793  0.153005 -0.322490  0.217108  0.002951  
4503  0.062066  0.561935  0.261236  0.187672 -0.305673  0.196493 -0.013865  

[5 rows x 100 columns]